language: node_js
cache:
  directories:
    - node_modules
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '8'
  - '7'
before_script:
  - greenkeeper-lockfile-update
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
  - npm install -g npm@5
  - npm install -g greenkeeper-lockfile@1
