language: node_js
cache: false
notifications:
  email: false
node_js:
  - 'stable'
  - 'lts/*'
before_script:
  - npm prune
  - greenkeeper-lockfile-update
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
before_install:
- npm install -g npm
- npm install -g greenkeeper-lockfile@1
after_script: greenkeeper-lockfile-upload
jobs:
  include:
    - stage: release
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
stages:
  - name: test
  - name: release
    if: branch = master
