name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
          node-version: ['lts/*', 'node']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Node ${{ matrix.node-version }} using nvm
      uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: ${{ matrix.node-version }}
    - run: |
        npm prune

    - run: |
        npm ci
        npm run lint
    - run: npm t
      env:
        CI: true
